# Generated by Django 4.1.7 on 2023-11-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='jugadores',
            field=models.JSONField(default=list),
        ),
    ]
